apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-test-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/dev
    repoURL: https://github.com/harysetiawan23/kustomize-test
    targetRevision: master
  sources: []
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
