# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-a
  namespace: dev
  labels:
    app: nginx-a
spec:
  selector:
    matchLabels:
      app: nginx-a
  replicas: 3
---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-b
  namespace: dev
  labels:
    app: nginx-b
spec:
  selector:
    matchLabels:
      app: nginx-b
  replicas: 2