apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-test-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/prod
    repoURL: https://github.com/harysetiawan23/kustomize-test
    targetRevision: master
  sources: []
  syncPolicy:
    syncOptions:
    - CreateNamespace=true