# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-a
  labels:
    app: nginx-a
spec:
  selector:
    matchLabels:
      app: nginx-a
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-b
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: nginx-a
        image: nginx:stable-alpine3.17
---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-b
  labels:
    app: nginx-b
spec:
  selector:
    matchLabels:
      app: nginx-b
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-b
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: nginx-b
        image: nginx:stable-alpine3.17