# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: nginx-a
spec:
  type: LoadBalancer
  ports:
  - name: nginx-a-lb
    protocol: TCP
    port: 80
    targetPort: 80
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: nginx-b
spec:
  type: LoadBalancer
  ports:
  - name: nginx-b-lb
    protocol: TCP
    port: 80
    targetPort: 80