# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: nginx-b
spec:
  selector:
    app: nginx-b
  type: LoadBalancer
  ports:
  - name: nginx-b
    protocol: TCP
    port: 8080
    targetPort: 80
